#ifndef _IOCTL_H
#define _IOCTL_H

#if defined(_MSC_VER)
// Ioctl value
#define IOCTL_MAYU_DETOUR_CANCEL					 \
CTL_CODE(FILE_DEVICE_KEYBOARD, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MAYU_GET_VERSION					 \
CTL_CODE(FILE_DEVICE_KEYBOARD, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_MAYU_GET_LOG					 \
CTL_CODE(FILE_DEVICE_KEYBOARD, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#else

#define CTL_CODE_GRAB_ON	(0x300000)

#define CTL_CODE_GRAB_OFF	(0x300001)

#endif

#endif // !_IOCTL_H
